import "./globals.css";
import Navbar from "./components/Navbar.tsx";
import { MyProvider } from "./components/Context.jsx";
import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
    <html lang="en">
       <MyProvider>
      <body
        className={inter.className}
      >
        <Navbar/>
        {children}
      </body>
      </MyProvider>
    </html>
 
  );
}
